[{ fname: 'Darcie', lname: 'Way', email: 'dmway1201@gmail.com' },
 { fname: 'Karen', lname: 'Opatik', email: 'karenopatik@gmail.com' },
 { fname: 'Ron', lname: 'Kooinenga', email: 'kooiengaron@gmail.com' },
 { fname: 'Marceille', lname: 'VanderTain', email: 'marcelle67@gmail.com' },
 { fname: 'Joann', lname: 'Newhouse', email: 'joannkayp@gmail.com' },
 { fname: 'Chris', lname: 'Palmer', email: 'christopher.palmer1@gmail.com' },
 { fname: 'Kristyn', lname: 'Haverkamp', email: 'krys_haverkamp@live.com' },
 { fname: 'La Nee', lname: 'Barlow', email: 'laneebarlow@gmail.com' },
 { fname: 'Josh', lname: 'Barlow', email: 'jvbarlow@gmail.com' },
 { fname: 'David', lname: 'Conklin', email: 'dlconklin@ftch.com' },
 { fname: 'Jusin', lname: 'Haverkamp', email: 'just_haverkamp@live.com' },
 { fname: 'Jim', lname: 'Haverkamp', email: 'haverkampj@sbcglobal.net' },
 { fname: 'Kelli', lname: 'Hoffman', email: 'kellihaverkamp@gmail.com' },
 { fname: 'Lynnell', lname: 'Haverkamp', email: 'nellbell.2@sbcglobal.net' }]
