AllCops:
  Exclude:
    - db/schema.rb
  EnabledByDefault: true
Bundler/GemComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrate/*
Style/DoubleNegation:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - spec/*
Style/MissingElse:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/Copyright:
  Enabled: false
