FROM ruby:2.7.0
RUN apt-get update -qq && apt-get install -y nodejs libpq-dev
RUN mkdir /app
WORKDIR /app
ADD ./Gemfile /app/Gemfile
ADD ./Gemfile.lock /app/Gemfile.lock
RUN bundle install --jobs 4
ADD . /app
