version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password3214
      - POSTGRES_USER=twentyliters
      - POSTGRES_DB=build_planner_dev
  web:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/start_docker 
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - DB_HOST=db
      - POSTGRES_PASSWORD=password3214
      - POSTGRES_USER=twentyliters

