# https://circleci.com/docs/2.0/language-ruby/
version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4
  browser-tools: circleci/browser-tools@1.1

jobs:
  # build:
  #   docker:
  #     - image: cimg/ruby:3.0.2-browsers


  #   steps:
  #     - browser-tools/install-chrome
  #     - browser-tools/install-chromedriver
  #     - checkout
  #     - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.0.2-browsers

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: chiperific
          POSTGRES_DB: build_planner_test
          POSTGRES_PASSWORD: ""

    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: chiperific
      PGPASSWORD: ''
      RAILS_ENV: test

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - ruby/install-deps

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      # - build
      - test:
          # requires:
            # - build
