development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: build-planner_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: build-planner_test

production:
  adapter: redis
  url: REDIS_URL
  channel_prefix: build-planner_production
