default: &default
  adapter: postgresql
  encoding: utf8
  prepared_statements: false
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: build_planner_dev

test:
  <<: *default
  database: build_planner_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:railway, :pg, :database) %>
  url: <%= Rails.application.credentials.dig(:railway, :pg, :url) %>
  host: <%= Rails.application.credentials.dig(:railway, :pg, :host) %>
  port: <%= Rails.application.credentials.dig(:railway, :pg, :port) %>
  username: <%= Rails.application.credentials.dig(:railway, :pg, :user) %>
  user: <%= Rails.application.credentials.dig(:railway, :pg, :user) %>
  password: <%= Rails.application.credentials.dig(:railway, :pg, :password) %>