default: &default
  adapter: postgresql
  encoding: utf8
  prepared_statements: false
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: build_planner_dev

test:
  <<: *default
  database: build_planner_test

production:
  <<: *default
  database: build_planner_prod
