development:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - mailers
  - bloomerang_job
  - count_create
  - count_transfer
  - email_sync
  - event_inventory
  - goal_remainder
  - price_calc
  - produceable
  - quantity_calc
  - registration_reminder
  - setup_reminder
:scheduler:
  :schedule:
    registration_reminders:
      description: "Run at 6:30am everyday. For events occurring in the next 2 days, send email reminders to any registrants who have not yet received them."
      cron: '30 6 * * *'
      class: RegistrationReminderJob
    setup_reminders:
      description: "Run at 5:30am everyday. For setups occurring in the next 2 days, send email reminders to any registered users who have not yet received them."
      cron: '30 5 * * *'
      class: SetupReminderJob
    sync_emails:
      description: "Run at 4am everyday. For each OauthUser, sync emails from Gmail to notes in Kindful when a matching person or organization is found."
      cron: '0 4 * * *'
      class: EmailSyncJob
    import_bloomerang:
      description: "Run at 2am every monday. import any new/updated Constituents; if it's the 1st Monday of the month: sync all Constituents."
      cron: '0 2 * * mon'
      class: BloomerangImportJob
